adri_tools_v2: adriiot_domoticz Class Reference
adriiot_domoticz Class Reference
#include <adriiot_main.h>
Public Member Functions
adriiot_domoticz ()
void update_module (DynamicJsonDocument json, int debug)
Detailed Description
Definition at line 174 of file adriiot_main.h.
Constructor & Destructor Documentation
adriiot_domoticz()
adriiot_domoticz::adriiot_domoticz ()
Definition at line 556 of file adriiot_modulemanagment.h.
{
         adriiot_domoticz_ptr = this;
 }
References adriiot_domoticz_ptr.
Member Function Documentation
update_module()
void adriiot_domoticz::update_module (DynamicJsonDocument json, int debug)
Definition at line 560 of file adriiot_modulemanagment.h.
{
                 // int c_1 = oject[F("idx")].as<int>();
                 // int c_2 = oject[F("nvalue")].as<int>();
                 // int c_3 = oject[F("svalue1")].as<int>();
                 // ADRI_LOG(3, 2, 1, "%d - %d - %d", c_1, c_2, c_3);
                 // adriiot_domoticz_ptr->update_module(c_1, c_2, c_3, 3);
         int idx         = oject[F("idx")].as<int>();
         int nValue      = oject[F("nvalue")].as<int>();
         int sValue      = oject[F("svalue1")].as<int>();
         JsonObject Color;
         int Color_b;
         int Color_g;
         int Color_r;
         moduleManagment * _module = adriiot_mainPtr->_moduleManagment;
         ADRI_LOG(debug, 0, 2, "update_module", "");
         for (int i = 0; i < _module->_pos; ++i) {
                 if (moduleClassArray[i]->_mqttidx == idx) {
                         int             id;
                         mSensorType      sType;
                         mType           moduleType;
                         moduleClassArray[i]->mType_get(moduleType);
                         moduleClassArray[i]->sType_get(sType);
                         moduleClassArray[i]->id_get(id);
                         String n = "";
                         moduleClassArray[i]->username_get(n);
                         ADRI_LOG(debug, 2, 1, "%s", n.c_str());
                         switch (moduleType) {
                             case mt_sensor:
                                 switch (sType) {
                                         case st_soilmoisture:
                                         break;
                                         case st_dht22:
                                         break;
                                         case st_ds18b20:
                                         break;
                                         default:
                                                 break;
                                 }
                             break;
                             case mt_relay:
                                 switch (nValue) {
                                     case 0:
                                         adriiot_mainPtr->_relayManagment->module(id)->close();
                                     break;
                                     case 1:
                                         adriiot_mainPtr->_relayManagment->module(id)->open();
                                     break;
                                     default:
                                         break;
                                 }
                             break;
                             case mt_lightDimmer:
                                 switch (nValue) {
                                     case 0:
                                         adriiot_mainPtr->_lightDimmerManagment->module(id)->close();
                                     break;
                                     case 1:
                                         adriiot_mainPtr->_lightDimmerManagment->module(id)->open();
                                     break;
                                     case 2:
                                         adriiot_mainPtr->_lightDimmerManagment->module(id)->dim(sValue);
                                     break;
                                     default:
                                         break;
                                 }
                             break;
                             case mt_lightRGB:
                                 switch (nValue) {
                                     case 10:
                                         ADRI_LOG(debug, 2, 1, "case 10", "");
                                         Color = oject[F("Color")];
                                                         Color_b = oject["Color"][F("b")].as<int>();
                                                         Color_g = oject["Color"][F("g")].as<int>();
                                                         Color_r = oject["Color"][F("r")].as<int>();
                                                         adriiot_mainPtr->_RGBneoManagment->module(id)->leds_rgb(Color_r, Color_g, Color_b, sValue);
                                     break;
                                     case 15:
                                         adriiot_mainPtr->_RGBneoManagment->module(id)->leds_bri(sValue);
                                     break;
                                     case 0:
                                         adriiot_mainPtr->_RGBneoManagment->module(id)->leds_black();
                                     break;
                                     case 1:
                                         adriiot_mainPtr->_RGBneoManagment->module(id)->leds_mod();
                                     break;
                                     default:
                                         break;
                                 }
                             break;
                             case mt_lightRGBW:
                             break;
                             default:
                                 break;
                         }
                         String s = "";
                         _module->json_modulesValue(i, s, debug);
                         _module->modulesValue[i] = s;
                         adriiot_mainPtr->dashboard_socket_update(i, debug);
                         _module->modulesValue_checkTimer->set_duration_max(5000);
                         // _module->modulesValue_checkTimer->activate();
                         break;
                 }
         }
         ADRI_LOG(debug, 1, 2, "update_module", "");
 }
References adriiot_main::_lightDimmerManagment, adriiot_main::_moduleManagment, moduleManagment::_pos, adriiot_main::_relayManagment, adriiot_main::_RGBneoManagment, adriiot_mainPtr, adriiot_main::dashboard_socket_update(), moduleClass::id_get(), moduleManagment::json_modulesValue(), moduleClassArray, moduleManagment::modulesValue, moduleManagment::modulesValue_checkTimer, mt_lightDimmer, mt_lightRGB, mt_lightRGBW, mt_relay, mt_sensor, moduleClass::mType_get(), st_dht22, st_ds18b20, st_soilmoisture, moduleClass::sType_get(), and moduleClass::username_get().
Referenced by adriiot_mqtt::domoticz_parse().
The documentation for this class was generated from the following files:
adriiot_main.h
adriiot_modulemanagment.h