adri_tools_v2: adriiot_mqtt Class Reference
adriiot_mqtt Class Reference
#include <adriiot_main.h>
Public Member Functions
adriiot_mqtt (const char *topicin, const char *topicout, const char *serverIp)
~adriiot_mqtt ()
void domoticz_parse (String json)
void connect ()
void reconnect ()
void loop ()
void publish (const char *payload)
void publish (String jsonStr)
Static Public Member Functions
static void callback (char *topic, byte *payload, unsigned int length)
Private Attributes
const char * _topicin = "in"
const char * _topicout = "out"
const char * _serverIp = "out"
PubSubClient * _client
uint16_t _serverPort = 1883
Detailed Description
Definition at line 184 of file adriiot_main.h.
Constructor & Destructor Documentation
adriiot_mqtt()
adriiot_mqtt::adriiot_mqtt (const char * topicin, const char * topicout, const char * serverIp)
Definition at line 286 of file adriiot_main.cpp.
{
         adriiot_mqtt_ptr = this;
         _topicin        = topicin;
         _topicout       = topicout;
         _serverIp       = serverIp;
         _client         = new PubSubClient(PubSubClient_espClient);
         fsprintf("\n[adriiot_mqtt::adriiot_mqtt] %s - %s - %s\n", _topicin, _topicout, _serverIp);
 }
References _client, _serverIp, _topicin, _topicout, adriiot_mqtt_ptr, and PubSubClient_espClient.
~adriiot_mqtt()
adriiot_mqtt::~adriiot_mqtt () inline
Definition at line 193 of file adriiot_main.h.
 {};
Member Function Documentation
callback()
void adriiot_mqtt::callback (char * topic, byte * payload, unsigned int length) static
Definition at line 329 of file adriiot_main.cpp.
{
         ADRI_LOG(2, -1, 0, "<<<", "");
         ADRI_LOG(2, 0, 2,"callback","");
         for (int i = 0; i < length; i++) {
                 adriiot_mqtt_packetBuffer[i]=(char)payload[i];
         }
         adriiot_mqtt_packetBuffer[length]=0;
         ADRI_LOGV(2, 2, 1, length, "", "");
         // fsprintf("%s\n", adriiot_mqtt_packetBuffer);
         adriiot_mqtt_ptr->domoticz_parse(adri_toolsv2Ptr_get()->ch_toString(adriiot_mqtt_packetBuffer));
         ADRI_LOG(2, 1, 2,"callback","");
         ADRI_LOG(2, -1, 0, ">>>", "");
 }
References adriiot_mqtt_packetBuffer, adriiot_mqtt_ptr, and domoticz_parse().
Referenced by connect().
connect()
void adriiot_mqtt::connect ()
Definition at line 314 of file adriiot_main.cpp.
{
         _client->setServer(_serverIp, _serverPort);
         _client->setCallback(callback);
 }
References _client, _serverIp, _serverPort, and callback().
Referenced by adriiot_main::wifiIsConnect().
domoticz_parse()
void adriiot_mqtt::domoticz_parse (String json)
Definition at line 342 of file adriiot_main.cpp.
{
         ADRI_LOG(3, -2, 0, "----<<<", "");
         ADRI_LOG(3, 0, 2,"domoticz_parse","");
         const size_t serializeSize = 512 * 4;
     DynamicJsonDocument oject(serializeSize);
     DeserializationError err = deserializeJson(oject, json);
     if (err) {
                 Serial.print(F("FLASHFS Error parsing settings json file: currentSetting.json"));
         Serial.println(err.c_str());
     } else {
                 // int c_1 = oject[F("idx")].as<int>();
                 // int c_2 = oject[F("nvalue")].as<int>();
                 // int c_3 = oject[F("svalue1")].as<int>();
                 // ADRI_LOG(3, 2, 1, "%d - %d - %d", c_1, c_2, c_3);
                 // adriiot_domoticz_ptr->update_module(c_1, c_2, c_3, 3);
                 adriiot_domoticz_ptr->update_module(oject, 3);
     }
     ADRI_LOG(3, 1, 2,"domoticz_parse","");
         ADRI_LOG(3, -2, 0, "---->>>", "");
 }
References adriiot_domoticz_ptr, and adriiot_domoticz::update_module().
Referenced by callback().
loop()
void adriiot_mqtt::loop ()
Definition at line 308 of file adriiot_main.cpp.
{
         if (!_client->connected()) {
                 reconnect();
         }
         _client->loop();
 }
References _client, and reconnect().
Referenced by adriiot_main::loop().
publish() [1/2]
void adriiot_mqtt::publish (const char * payload)
Definition at line 319 of file adriiot_main.cpp.
{
         _client->publish(_topicin, payload);
 }
References _client, and _topicin.
Referenced by moduleManagment::json_domoticz_modulesValue(), and adriiot_main::mqqt_send().
publish() [2/2]
void adriiot_mqtt::publish (String jsonStr)
Definition at line 322 of file adriiot_main.cpp.
{
         char buffer[512];
         sprintf(buffer, "%s", jsonStr.c_str());
         _client->publish(_topicin, buffer);
 }
References _client, and _topicin.
reconnect()
void adriiot_mqtt::reconnect ()
Definition at line 294 of file adriiot_main.cpp.
{
         while (!_client->connected()) {
                         fsprintf("\n[adriiot_mqtt]\n\tconnection in progress\n");
                         String clientId = "ESP8266Client-";
                         clientId += String(random(0xffff), HEX);
                 if (_client->connect(clientId.c_str())) {
                         fsprintf("\n[adriiot_mqtt]\n\tconnection success\n");
                         _client->subscribe("domoticz/out");
                 } else {
                         fsprintf("\n[adriiot_mqtt]\n\tconnection failed, rc= %d\n", _client->state());
                         delay(5000);
                 }
         }
 }
References _client.
Referenced by loop().
Member Data Documentation
_client
PubSubClient* adriiot_mqtt::_client private
Definition at line 189 of file adriiot_main.h.
Referenced by adriiot_mqtt(), connect(), loop(), publish(), and reconnect().
_serverIp
const char* adriiot_mqtt::_serverIp = "out" private
Definition at line 188 of file adriiot_main.h.
Referenced by adriiot_mqtt(), and connect().
_serverPort
uint16_t adriiot_mqtt::_serverPort = 1883 private
Definition at line 190 of file adriiot_main.h.
Referenced by connect().
_topicin
const char* adriiot_mqtt::_topicin = "in" private
Definition at line 186 of file adriiot_main.h.
Referenced by adriiot_mqtt(), and publish().
_topicout
const char* adriiot_mqtt::_topicout = "out" private
Definition at line 187 of file adriiot_main.h.
Referenced by adriiot_mqtt().
The documentation for this class was generated from the following files:
adriiot_main.h
adriiot_main.cpp