adri_tools_v2: wifiClass Class Reference
wifiClass Class Reference
#include <wifi.h>
Public Member Functions
wifiClass (const char *value)
~wifiClass ()
mod_wifiConnect_error error_get ()
void _connectMod_set (int value)
int _connectMod_get ()
void _hostname_get (String &ret)
void _otaEnabled_set (boolean ret)
boolean _setupFromSpiff ()
boolean _setup (WIFICONNECT_MOD cMod=AWC_SETUP, WIFICONNECTSSID_MOD sMod=AWCS_NORMAL)
boolean _setupAp (WIFICONNECT_MOD cMod=AWC_SETUP, WIFICONNECTSSID_MOD sMod=AWCS_NORMAL)
boolean _connect (WIFICONNECT_MOD cMod)
void _connect_arduinoIOT ()
boolean _connectFromSpiff ()
void _loop ()
void _checkConnected_start ()
boolean _checkConnected (int &result)
void _checkConnected_loop ()
void ntpTime_setup ()
void ntpTime_loop ()
void ntpTime_getTime (String &ret)
String ntpTime_toString (time_t t)
boolean ntpTime_isSet ()
Public Attributes
const char * _hostname = "HELLOWORLD"
boolean _isConnect = false
int _connectMod = 0
int _eventModStart = 0
boolean _otaEnabled = true
Private Attributes
mod_wifiConnect_error _error_setup = mwce_none
adri_timer * _checkConnected_timer = nullptr
int _connectMod_setTo = 0
adri_timer * _connectModTimer = nullptr
adri_timeNtp * _ntpTime
Detailed Description
Definition at line 15 of file wifi.h.
Constructor & Destructor Documentation
wifiClass()
wifiClass::wifiClass (const char * value)
Definition at line 11 of file wifi.cpp.
                                        : wifiConnect(){
         wifiClass_ptr = this;
         _checkConnected_timer   = new adri_timer(180000,        "", false);
         _connectModTimer                = new adri_timer(2000,          "", false);
         _hostname                               = value;
         _connectMod                     = 0;
         new wifi_credential_ap("");
         _ntpTime                                = new adri_timeNtp();
 }
References _checkConnected_timer, _connectMod, _connectModTimer, _hostname, _ntpTime, and wifiClass_ptr.
~wifiClass()
wifiClass::~wifiClass () inline
Definition at line 35 of file wifi.h.
 {};
Member Function Documentation
_checkConnected()
boolean wifiClass::_checkConnected (int & result)
Definition at line 222 of file wifi.cpp.
{
     WiFiClient client;
     HTTPClient http;
         if (http.begin(client, "http://jigsaw.w3.org/HTTP/connection.html")) {  // HTTP
                 result = http.GET();
                 http.end();
                 return true;
         } else {
                 result = -2;
                 return false;
         }
 }
_checkConnected_loop()
void wifiClass::_checkConnected_loop ()
Definition at line 234 of file wifi.cpp.
{
         if (!_checkConnected_timer->isActivate()) return;
         // if (_checkConnected_timer->loop()) {
         //      int result = -1;
         //      boolean check = _checkConnected(result);
         //      if ((!check) || (result <= 0)) {
         //              char buffer[200];
         //              String timeStr;
         //              ntpTime_getTime(timeStr);
         //              int wD, sMon, sYear;
         //              adri_timeNtp_instance()->dateGet(wD, sMon, sYear);
         //              String timeStamp = String(wD)+"/"+String(sMon)+"/"+String(sYear)+"_"+timeStr;
         //              sprintf(buffer, "[_checkConnected_loop] begin: %d - result: %d", check, result);
         //              fsprintf("\n%s\n", buffer);
         //              String logStr = "";
         //              adri_toolsv2Ptr_get()()->log_read(logStr, false);
         //              adri_toolsv2Ptr_get()()->log_write(logStr, timeStamp, String(buffer));
         //              ESP.restart();
         //      }
         // }
 }
References _checkConnected_timer.
_checkConnected_start()
void wifiClass::_checkConnected_start ()
Definition at line 217 of file wifi.cpp.
{
         WiFiMode_t wifiMod = WiFi.getMode();
         if (wifiMod == WIFI_AP) return;
         _checkConnected_timer->activate();
 }
References _checkConnected_timer.
_connect()
boolean wifiClass::_connect (WIFICONNECT_MOD cMod)
Definition at line 117 of file wifi.cpp.
{
         // lampPeripheralsInstance()->oled_clear();
         // lampPeripheralsInstance()->wificonnect("Connect wifiClass en cour");
         if (cMod == AWC_SETUP) {
                 setup();
                 // lampPeripheralsInstance()->oled_clear();
                 // lampPeripheralsInstance()->wifiPrint();
                 if(!_otaEnabled)        MDSN_begin                      ();
                 else                            arduinoOTA_setup        (_hostname);
                 ntpTime_setup();
                 _connectModTimer->set_duration_max(2000);
                 _connectModTimer->activate();
                 _connectMod             = 0;
                 _connectMod_setTo       = 1;
         }
         if (cMod == AWC_LOOP) {
                 _connectModTimer->set_duration_max(2000);
                 _connectModTimer->activate();
                 _connectMod             = 0;
                 _connectMod_setTo       = 2;
         }
         return true;
 }
References _connectMod, _connectMod_setTo, _connectModTimer, _hostname, _otaEnabled, and ntpTime_setup().
Referenced by _connectFromSpiff(), and adriiot_main::wifiConnect().
_connect_arduinoIOT()
void wifiClass::_connect_arduinoIOT ()
Definition at line 149 of file wifi.cpp.
{
         if (wifi_connect_result("") ) {
                 if(!_otaEnabled)        MDSN_begin                      ();
                 else                            arduinoOTA_setup        (_hostname);
                 ntpTime_setup();
         }
 }
References _hostname, _otaEnabled, and ntpTime_setup().
_connectFromSpiff()
boolean wifiClass::_connectFromSpiff ()
Definition at line 160 of file wifi.cpp.
{
         // lampPeripheralsInstance()->oled_clear();
         // lampPeripheralsInstance()->wificonnect("Connect wifiClass en cour");
         String s;
         WIFICONNECTSSID_MOD_toString(_connectSSID, s);
         fsprintf("DEBUG:%s\n",s.c_str());
         WIFICONNECT_MOD_toString(wifiConnect_instance()->_connect, s);
         fsprintf("DEBUG:%s\n",s.c_str());
         _connect(wifiConnect_instance()->_connect);
         if (_connectSSID==AWCS_AP) {
         } else {
         }
         return true;
 }
References _connect().
_connectMod_get()
int wifiClass::_connectMod_get ()
Definition at line 27 of file wifi.cpp.
 { return _connectMod; }
References _connectMod.
_connectMod_set()
void wifiClass::_connectMod_set (int value)
Definition at line 29 of file wifi.cpp.
 { _connectMod = value; }
References _connectMod.
_hostname_get()
void wifiClass::_hostname_get (String & ret)
Definition at line 31 of file wifi.cpp.
 { ret = adri_toolsv2Ptr_get()->ch_toString(_hostname);}
References _hostname.
_loop()
void wifiClass::_loop ()
Definition at line 178 of file wifi.cpp.
                       {
         if ( _connectModTimer->isActivate() ) {
                 if ( _connectModTimer->loop_stop() ) {
                         _connectMod = _connectMod_setTo;
                         switch(_connectMod) {
                                 case 1:
                                 break;
                                 case 2:
                                         setupLoop();
                                 break;
                         }
                 }
         }
         wifi_loop();
         if ((!_isConnect) && (wifi_loop_statu()==wifi_statu_sta_isconnected) && (_connectMod == 2)) {
                 _connectMod = 3;
                 // fsprintf("\n[wifi_loop_statu : wifi_statu_sta_isconnected]\n")
                 // lampPeripheralsInstance()->oled_clear();
                 // lampPeripheralsInstance()->wifiPrint();
                 if(!_otaEnabled)        MDSN_begin                      ();
                 else                            arduinoOTA_setup        (_hostname);
                 ntpTime_setup();
                 _connectModTimer->set_duration_max(1500);
                 _connectModTimer->activate();
                 _connectMod_setTo       = 1;
         }
 }
References _connectMod, _connectMod_setTo, _connectModTimer, _hostname, _isConnect, _otaEnabled, and ntpTime_setup().
Referenced by adriiot_main::loop().
_otaEnabled_set()
void wifiClass::_otaEnabled_set (boolean ret)
Definition at line 33 of file wifi.cpp.
 { _otaEnabled = ret;}
References _otaEnabled.
_setup()
boolean wifiClass::_setup (WIFICONNECT_MOD cMod = AWC_SETUP, WIFICONNECTSSID_MOD sMod = AWCS_NORMAL)
Definition at line 35 of file wifi.cpp.
{
         if (!wifi_credential_sta_fromSPIFF()){
                 wifi_credential_set(
                         0,
                         "",
                         "",
                         "",
                         "",
                         ""
                 );
                 wifi_credential_sta_toSpiff();
                 return false;
         }
         // wifi_credential_sta_print();
         credential_sta_pos_set          (0);
         connect_set                             (cMod);
         connectSSID_set                         (sMod);
         station_set                             (WIFI_STA);
         hostName_set                            (_hostname);
         setup_id                                        ();
         // print_cfg                                    ();
         // if (!_ap->load_fromSpiif()) {
         wifi_credentialAp_ptr_get()->hostname_set(adri_toolsv2Ptr_get()->ch_toString(_hostname));
         wifi_credentialAp_ptr_get()->psk_set("adriiot1234");
         wifi_credentialAp_ptr_get()->ip_set("192.168.4.1");
         // wifi_credentialAp_ptr_get()->print();
         return true;
 }
References _hostname.
Referenced by _setupFromSpiff().
_setupAp()
boolean wifiClass::_setupAp (WIFICONNECT_MOD cMod = AWC_SETUP, WIFICONNECTSSID_MOD sMod = AWCS_NORMAL)
Definition at line 104 of file wifi.cpp.
{
         credential_sta_pos_set          (0);
         connect_set                             (cMod);
         connectSSID_set                         (sMod);
         station_set                             (WIFI_STA);
         hostName_set                            (_hostname);
         setup_id();
         wifi_credentialAp_ptr_get()->hostname_set(adri_toolsv2Ptr_get()->ch_toString(_hostname));
         wifi_credentialAp_ptr_get()->psk_set("adriiot1234");
         wifi_credentialAp_ptr_get()->ip_set("192.168.4.1");
         return true;
 }
References _hostname.
Referenced by adriiot_main::wifiConnect().
_setupFromSpiff()
boolean wifiClass::_setupFromSpiff ()
Definition at line 69 of file wifi.cpp.
{
         String s;
         if (!wifi_credential_sta_fromSPIFF()){
                 wifi_credential_set(
                         0,
                         "",
                         "",
                         "",
                         "",
                         ""
                 );
                 wifi_credential_sta_toSpiff();
         }
         if (!wifiConnect_load_fromSPIFF(s))                             return false;
         if (adri_toolsv2Ptr_get()->literal_value("connectSSID", s) == "ap")     return false;
         // fsprintf("\n[_setupFromSpiff connectSSID]%s\n", adri_toolsv2Ptr_get()->literal_value("connectSSID", s).c_str());
         // fsprintf("\n[_setupFromSpiff connect]%s\n",  adri_toolsv2Ptr_get()->literal_value("connect", s).c_str());
         if (adri_toolsv2Ptr_get()->literal_value("connectSSID", s) == "loop") {
                 connect_set     (AWC_LOOP);
                 connectSSID_set (AWCS_NORMAL);
                 if (!_setup(AWC_LOOP, AWCS_NORMAL)) return false;
         }
         else if (adri_toolsv2Ptr_get()->literal_value("connectSSID", s) == "setup") {
                 connect_set     (AWC_SETUP);
                 connectSSID_set (AWCS_NORMAL);
                 if (!_setup(AWC_SETUP, AWCS_NORMAL)) return false;
         }
         else {
                 connect_set     (AWC_SETUP);
                 connectSSID_set (AWCS_NORMAL);
                 if (!_setup(AWC_SETUP, AWCS_NORMAL)) return false;
         }
         return true;
 }
References _setup().
Referenced by adriiot_main::wifiConnect().
error_get()
mod_wifiConnect_error wifiClass::error_get ()
Definition at line 23 of file wifi.cpp.
{
         return _error_setup;
 }
References _error_setup.
ntpTime_getTime()
void wifiClass::ntpTime_getTime (String & ret)
Definition at line 272 of file wifi.cpp.
{
         time_t  time;
         if (ntpTime_isSet()){
                 time    = adri_timeNtp_instance()->timeget();
                 ret     = ntpTime_toString(time);
         } else {
                 ret = "";
         }
 }
References ntpTime_isSet(), and ntpTime_toString().
ntpTime_isSet()
boolean wifiClass::ntpTime_isSet ()
Definition at line 286 of file wifi.cpp.
{
         boolean ret = false;
         if(     _ntpTime->time_isSet ) {
                 ret = true;
         } else {
                 ret = false;
         }
         return ret;
 }
References _ntpTime.
Referenced by ntpTime_getTime(), and ntpTime_loop().
ntpTime_loop()
void wifiClass::ntpTime_loop ()
Definition at line 268 of file wifi.cpp.
{
         if (!ntpTime_isSet()) return;
         _ntpTime->loop();
 }
References _ntpTime, and ntpTime_isSet().
Referenced by adriiot_main::loop().
ntpTime_setup()
void wifiClass::ntpTime_setup ()
Definition at line 264 of file wifi.cpp.
{
         boolean sWifi = wifi_connect_result("");
         _ntpTime->setup(sWifi);
 }
References _ntpTime.
Referenced by _connect(), _connect_arduinoIOT(), _loop(), and adriiot_main::loop().
ntpTime_toString()
String wifiClass::ntpTime_toString (time_t t)
Definition at line 281 of file wifi.cpp.
{
     char tmpStr[100];
     sprintf(tmpStr, "%02d:%02d:%02d", hour(t), minute(t), second(t));
     return String(tmpStr);
 }
Referenced by ntpTime_getTime().
Member Data Documentation
_checkConnected_timer
adri_timer* wifiClass::_checkConnected_timer = nullptr private
Definition at line 20 of file wifi.h.
Referenced by _checkConnected_loop(), _checkConnected_start(), and wifiClass().
_connectMod
int wifiClass::_connectMod = 0
Definition at line 30 of file wifi.h.
Referenced by _connect(), _connectMod_get(), _connectMod_set(), _loop(), adriiot_main::loop(), wifiClass(), and adriiot_main::wifiIsConnect().
_connectMod_setTo
int wifiClass::_connectMod_setTo = 0 private
Definition at line 22 of file wifi.h.
Referenced by _connect(), and _loop().
_connectModTimer
adri_timer* wifiClass::_connectModTimer = nullptr private
Definition at line 23 of file wifi.h.
Referenced by _connect(), _loop(), and wifiClass().
_error_setup
mod_wifiConnect_error wifiClass::_error_setup = mwce_none private
Definition at line 18 of file wifi.h.
Referenced by error_get().
_eventModStart
int wifiClass::_eventModStart = 0
Definition at line 31 of file wifi.h.
_hostname
const char* wifiClass::_hostname = "HELLOWORLD"
Definition at line 28 of file wifi.h.
Referenced by _connect(), _connect_arduinoIOT(), _hostname_get(), _loop(), _setup(), _setupAp(), adriiot_main::loop(), and wifiClass().
_isConnect
boolean wifiClass::_isConnect = false
Definition at line 29 of file wifi.h.
Referenced by _loop(), and adriiot_main::loop().
_ntpTime
adri_timeNtp* wifiClass::_ntpTime private
Definition at line 25 of file wifi.h.
Referenced by ntpTime_isSet(), ntpTime_loop(), ntpTime_setup(), and wifiClass().
_otaEnabled
boolean wifiClass::_otaEnabled = true
Definition at line 32 of file wifi.h.
Referenced by _connect(), _connect_arduinoIOT(), _loop(), _otaEnabled_set(), and adriiot_main::loop().
The documentation for this class was generated from the following files:
wifi.h
wifi.cpp