adri_tools_v2: moduleManagment Class Reference
moduleManagment Class Reference
#include <adriiot_main.h>
Public Member Functions
moduleManagment ()
~moduleManagment ()
void modulesValue_check ()
void mqqt_setidx (int idx)
void create (mModule mName, mType moType, mRelayType rType, mSensorType sType, int pin, int numLeds, String username, int idx=-1)
void create (mModule mName, mType moType, mRelayType rType, mSensorType sType, int pin, String username, int idx=-1)
void create_lightRGB (int pin, int numLeds, String username, int idx=-1)
void create_lightDimmer (int pin, String username, int idx=-1)
void create_temperature (int pin, String username, int idx=-1)
void create_temperatureEx (int pin, String username, int idx=-1)
void create_plug (int pin, String username, int idx=-1)
void create_light (int pin, String username, int idx=-1)
void create_light (mType type, int pin, String username, int idx=-1)
void create_sensor (mSensorType type, int pin, String username, int idx=-1)
moduleClass * module (int pos)
void toggleRelay (unsigned long delay)
void print ()
int currentCnt ()
void json_modules (String &ret, int debug=-1)
void jsonObject_modules (JsonObject &root)
void json_modulesValue (String &ret, int debug=-1)
void jsonObject_modulesValue (JsonObject &root)
void json_modulesValue (int pos, String &ret, int debug=-1)
void jsonObject_modulesValue (int pos, JsonObject &root)
void json_modulesValue (String pos, String &ret, int debug=-1)
void jsonObject_modulesValue (String pos, JsonObject &root)
void json_modulesValueList (String &ret, int debug=-1)
void json_domoticz_modulesValue (int pos, String &ret, int debug=-1)
void jsonObject_domoticz_modulesValue (int pos, JsonObject &root)
void json_domoticz_modulesValue (String &ret, int debug=-1)
void jsonObject_domoticz_modulesValue (JsonObject &root)
void json_mName (String &ret)
void jsonObject_mName (JsonObject &root)
void json_mType (String &ret)
void jsonObject_mType (JsonObject &root)
void jsonObject_rtype (JsonObject &object)
void json_rType (String &ret)
void jsonObject_stype (JsonObject &object)
void json_sType (String &ret)
void getByName (String search, int &ret)
void getIdByName (String search, int &ret)
void getIdByPos (int search, int &ret)
void mNameToString (mModule value, String &result)
void mTypeToString (mType value, String &result)
void rTypeToString (mRelayType value, String &result)
void sTypeToString (mSensorType value, String &result)
void domoticz_modules_upadte (int idx, int nValue, int sValue)
Public Attributes
int _pos = 0
boolean modulesValue_check_skip = false
String modulesValue [MAX_MODULE]
adri_timer * modulesValue_checkTimer
Detailed Description
Definition at line 95 of file adriiot_main.h.
Constructor & Destructor Documentation
moduleManagment()
moduleManagment::moduleManagment ()
Definition at line 12 of file adriiot_modulemanagment.h.
{
         modulesValue_checkTimer = new adri_timer(1000, "", true);
 }
References modulesValue_checkTimer.
~moduleManagment()
moduleManagment::~moduleManagment () inline
Definition at line 101 of file adriiot_main.h.
 {};
Member Function Documentation
create() [1/2]
void moduleManagment::create (mModule mName, mType moType, mRelayType rType, mSensorType sType, int pin, int numLeds, String username, int idx = -1)
Definition at line 32 of file adriiot_modulemanagment.h.
{
         moduleClassArray[_pos] = new moduleClass(mName, moType, rType, sType, pin, numLeds, username);
         moduleClassArray[_pos]->_mqttidx = idx;
         _pos++;
 }
References moduleClass::_mqttidx, _pos, and moduleClassArray.
Referenced by create_light(), create_lightDimmer(), create_lightRGB(), create_plug(), create_sensor(), create_temperature(), create_temperatureEx(), and moduleManagment_spiff::load().
create() [2/2]
void moduleManagment::create (mModule mName, mType moType, mRelayType rType, mSensorType sType, int pin, String username, int idx = -1)
Definition at line 37 of file adriiot_modulemanagment.h.
{
         moduleClassArray[_pos] = new moduleClass(mName, moType, rType, sType, pin, username);
         moduleClassArray[_pos]->_mqttidx = idx;
         _pos++;
 }
References moduleClass::_mqttidx, _pos, and moduleClassArray.
create_light() [1/2]
void moduleManagment::create_light (int pin, String username, int idx = -1)
Definition at line 26 of file adriiot_modulemanagment.h.
 {create(mn_relay,       mt_relay,               rt_light,       st_unk,                 pin, username, idx);}
References create(), mn_relay, mt_relay, rt_light, and st_unk.
create_light() [2/2]
void moduleManagment::create_light (mType type, int pin, String username, int idx = -1)
Definition at line 27 of file adriiot_modulemanagment.h.
{
                                                                                                                                                                 create(mn_light,        type,                   rt_unk,         st_unk,                 pin, username, idx);}
References create(), mn_light, rt_unk, and st_unk.
create_lightDimmer()
void moduleManagment::create_lightDimmer (int pin, String username, int idx = -1)
Definition at line 22 of file adriiot_modulemanagment.h.
 {create(mn_light,       mt_lightDimmer, rt_unk,         st_unk,                 pin, username, idx);}
References create(), mn_light, mt_lightDimmer, rt_unk, and st_unk.
create_lightRGB()
void moduleManagment::create_lightRGB (int pin, int numLeds, String username, int idx = -1)
Definition at line 20 of file adriiot_modulemanagment.h.
{
                                                                                                                                                                 create(mn_light,        mt_lightRGB,    rt_unk,         st_unk,                 pin, numLeds, username, idx);}
References create(), mn_light, mt_lightRGB, rt_unk, and st_unk.
create_plug()
void moduleManagment::create_plug (int pin, String username, int idx = -1)
Definition at line 25 of file adriiot_modulemanagment.h.
 {create(mn_relay,       mt_relay,               rt_plug,        st_unk,                 pin, username, idx);}
References create(), mn_relay, mt_relay, rt_plug, and st_unk.
create_sensor()
void moduleManagment::create_sensor (mSensorType type, int pin, String username, int idx = -1)
Definition at line 29 of file adriiot_modulemanagment.h.
{
                                                                                                                                                                 create(mn_sensor,       mt_sensor,              rt_unk,         type,                   pin, username, idx);}
References create(), mn_sensor, mt_sensor, and rt_unk.
create_temperature()
void moduleManagment::create_temperature (int pin, String username, int idx = -1)
Definition at line 23 of file adriiot_modulemanagment.h.
 {create(mn_sensor,      mt_sensor,              rt_unk,         st_dht22,               pin, username, idx);}
References create(), mn_sensor, mt_sensor, rt_unk, and st_dht22.
create_temperatureEx()
void moduleManagment::create_temperatureEx (int pin, String username, int idx = -1)
Definition at line 24 of file adriiot_modulemanagment.h.
 {create(mn_sensor,      mt_sensor,              rt_unk,         st_ds18b20,             pin, username, idx);}
References create(), mn_sensor, mt_sensor, rt_unk, and st_ds18b20.
currentCnt()
int moduleManagment::currentCnt ()
Definition at line 16 of file adriiot_modulemanagment.h.
 {return _pos;}
References _pos.
Referenced by moduleClass::moduleClass().
domoticz_modules_upadte()
void moduleManagment::domoticz_modules_upadte (int idx, int nValue, int sValue)
getByName()
void moduleManagment::getByName (String search, int & ret)
Definition at line 45 of file adriiot_modulemanagment.h.
{
         String name = "";
         for (int i = 0; i < _pos; ++i) {
                 name = "";
                 moduleClassArray[i]->username_get(name);
                 if (search == name) {ret = i; break;}
         }
 }
References _pos, moduleClassArray, and moduleClass::username_get().
Referenced by json_modulesValue(), and jsonObject_modulesValue().
getIdByName()
void moduleManagment::getIdByName (String search, int & ret)
Definition at line 53 of file adriiot_modulemanagment.h.
{
         String name = "";
         for (int i = 0; i < _pos; ++i) {
                 name = "";
                 moduleClassArray[i]->username_get(name);
                 if (search == name) {moduleClassArray[i]->id_get(ret); break;}
         }
 }
References _pos, moduleClass::id_get(), moduleClassArray, and moduleClass::username_get().
getIdByPos()
void moduleManagment::getIdByPos (int search, int & ret)
Definition at line 61 of file adriiot_modulemanagment.h.
{
         moduleClassArray[search]->id_get(ret);
 }
References moduleClass::id_get(), and moduleClassArray.
json_domoticz_modulesValue() [1/2]
void moduleManagment::json_domoticz_modulesValue (int pos, String & ret, int debug = -1)
Definition at line 245 of file adriiot_modulemanagment.h.
{
         ADRI_LOG(debug, 0, 2, "", "");
         DynamicJsonDocument json(json_moduleValue_size);
         JsonObject root = json.to<JsonObject>();
         jsonObject_domoticz_modulesValue(pos, root);
         ret= "";
         serializeJson(json, ret);
         ADRI_LOG(debug, 2, 2, "%s\n", ret.c_str());
         ADRI_LOG(debug, 1, 2, "", "");
 }
References jsonObject_domoticz_modulesValue().
Referenced by adriiot_main::dashboard_webClient_update().
json_domoticz_modulesValue() [2/2]
void moduleManagment::json_domoticz_modulesValue (String & ret, int debug = -1)
Definition at line 209 of file adriiot_modulemanagment.h.
{
         ADRI_LOG(debug, 0, 2, "", "");
         DynamicJsonDocument json(json_modulesValue_size);
         String          jsonStr;
         int             id;
         String          username;
         char            buffer[512];
         mSensorType      sType;
         for (int i = 0; i < _pos; ++i) {
                 JsonObject root = json.to<JsonObject>();
                 moduleClassArray[i]->id_get(id);
                 moduleClassArray[i]->sType_get(sType);
                 moduleClassArray[i]->username_get(username);
                 moduleClassArray[i]->json_domoticz_value(root);
                 jsonStr = "";
                 serializeJson(json, jsonStr);
                 sprintf(buffer, "%s", jsonStr.c_str());
                 adriiot_mainPtr->_adriiot_mqtt->publish(buffer);
                 ADRI_LOG(debug, 2, 2, "\t[MQTT][%18s] json: %s\n", username.c_str(), buffer);
         }
         ADRI_LOG(debug, 1, 2, "", "");
 }
References adriiot_main::_adriiot_mqtt, _pos, adriiot_mainPtr, moduleClass::id_get(), moduleClass::json_domoticz_value(), moduleClassArray, adriiot_mqtt::publish(), moduleClass::sType_get(), and moduleClass::username_get().
json_mName()
void moduleManagment::json_mName (String & ret)
Definition at line 313 of file adriiot_modulemanagment.h.
{
         const size_t serializeSize = 512 * 2;
         DynamicJsonDocument json(serializeSize);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject(F("mName"));
         jsonObject_mName(object);
         ret= "";
         serializeJson(json, ret);
         #ifdef DEBUG
                 fsprintf("\n[moduleManagment::json_mName]\n%s\n", ret.c_str());
                 String v="";
                 for (int i = mn_sensor; i < mn_unk; ++i) {
                         mNameToString(mModuleArray[i],  v);
                         fsprintf("\t[%15s][%d]\n",v.c_str(),mModuleArray[i]);
                 }
         #endif
 }
References jsonObject_mName(), mModuleArray, mn_sensor, mn_unk, and mNameToString().
json_modules()
void moduleManagment::json_modules (String & ret, int debug = -1)
Definition at line 179 of file adriiot_modulemanagment.h.
{
         ADRI_LOG(debug, 0, 2, "", "");
         DynamicJsonDocument json(json_modules_size);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject("mListe");
         jsonObject_modules(object);
         ret= "";
         serializeJson(json, ret);
         ADRI_LOG(debug, 2, 2, "\n%s\n", ret.c_str());
         ADRI_LOG(debug, 1, 2, "", "");
 }
References jsonObject_modules().
json_modulesValue() [1/3]
void moduleManagment::json_modulesValue (int pos, String & ret, int debug = -1)
Definition at line 135 of file adriiot_modulemanagment.h.
{
         ADRI_LOG(debug, 0, 2, "", "");
         DynamicJsonDocument json(json_moduleValue_size);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject("mValue");
         jsonObject_modulesValue(pos, object);
         ret= "";
         serializeJson(json, ret);
         ADRI_LOG(debug, 2, 2, "\n%s\n", ret.c_str());
         ADRI_LOG(debug, 1, 2, "", "");
 }
References jsonObject_modulesValue().
json_modulesValue() [2/3]
void moduleManagment::json_modulesValue (String & ret, int debug = -1)
Definition at line 113 of file adriiot_modulemanagment.h.
{
         ADRI_LOG(debug, 0, 2, "", "");
         DynamicJsonDocument json(json_modulesValue_size);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject("mValues");
         jsonObject_modulesValue(object);
         ret= "";
         serializeJson(json, ret);
         ADRI_LOG(debug, 2, 2, "\n%s\n", ret.c_str());
         ADRI_LOG(debug, 1, 2, "", "");
 }
References jsonObject_modulesValue().
Referenced by adriiot_main::dashboard_socket_update(), adriiot_main::dashboard_webClient_update(), modulesValue_check(), and adriiot_domoticz::update_module().
json_modulesValue() [3/3]
void moduleManagment::json_modulesValue (String pos, String & ret, int debug = -1)
Definition at line 156 of file adriiot_modulemanagment.h.
{
         ADRI_LOG(debug, 0, 2, "", "");
         int pos = -1;
         getByName(name, pos);
         if (pos == -1) {ADRI_LOG(debug, 1, 2, "", "");return;}
         DynamicJsonDocument json(json_moduleValue_size);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject("mValue");
         jsonObject_modulesValue(name, object);
         ret= "";
         serializeJson(json, ret);
         ADRI_LOG(debug, 2, 2, "\n%s\n", ret.c_str());
         ADRI_LOG(debug, 1, 2, "", "");
 }
References getByName(), and jsonObject_modulesValue().
json_modulesValueList()
void moduleManagment::json_modulesValueList (String & ret, int debug = -1)
Definition at line 88 of file adriiot_modulemanagment.h.
{
         ADRI_LOG(debug, 0, 2, "", "");
         DynamicJsonDocument json(512 * 20);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject("mValues");
         jsonObject_modulesValue(object);
         object = root.createNestedObject("mListe");
         jsonObject_modules(object);
         ret= "";
         serializeJson(json, ret);
         ADRI_LOG(debug, 2, 2, "\n%s\n", ret.c_str());
         ADRI_LOG(debug, 1, 2, "", "");
 }
References jsonObject_modules(), and jsonObject_modulesValue().
json_mType()
void moduleManagment::json_mType (String & ret)
Definition at line 347 of file adriiot_modulemanagment.h.
{
         const size_t serializeSize = 512 * 2;
         DynamicJsonDocument json(serializeSize);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject(F("mType"));
         jsonObject_mType(object);
         ret= "";
         serializeJson(json, ret);
         #ifdef DEBUG
                 fsprintf("\n[moduleManagment::json_mType]\n%s\n", ret.c_str());
                 String v="";
                 for (int i = mt_sensor; i < mt_unk; ++i) {
                         mTypeToString(mTypeArray[i],  v);
                         fsprintf("\t[%15s][%d]\n",v.c_str(),mTypeArray[i]);
                 }
         #endif
 }
References jsonObject_mType(), mt_sensor, mt_unk, mTypeArray, and mTypeToString().
json_rType()
void moduleManagment::json_rType (String & ret)
Definition at line 378 of file adriiot_modulemanagment.h.
{
         const size_t serializeSize = 512 * 2;
         DynamicJsonDocument json(serializeSize);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject(F("mRelayType"));
         jsonObject_rtype(object);
         ret= "";
         serializeJson(json, ret);
         #ifdef DEBUG
                 fsprintf("\n[moduleManagment::json_rType]\n%s\n", ret.c_str());
                 String v="";
                 for (int i = rt_light; i < rt_unk; ++i) {
                         rTypeToString(rTypeArray[i],  v);
                         fsprintf("\t[%15s][%d]\n",v.c_str(),rTypeArray[i]);
                 }
         #endif
 }
References jsonObject_rtype(), rt_light, rt_unk, rTypeArray, and rTypeToString().
json_sType()
void moduleManagment::json_sType (String & ret)
Definition at line 411 of file adriiot_modulemanagment.h.
{
         const size_t serializeSize = 512 * 2;
         DynamicJsonDocument json(serializeSize);
         JsonObject root = json.to<JsonObject>();
         JsonObject object = root.createNestedObject(F("mSensorType"));
         jsonObject_stype(object);
         ret= "";
         serializeJson(json, ret);
         #ifdef DEBUG
                 fsprintf("\n[moduleManagment::json_sType]\n%s\n", ret.c_str());
                 String v="";
                 for (int i = st_soilmoisture; i < st_unk; ++i) {
                         sTypeToString(sensorTypeArray[i],  v);
                         fsprintf("\t[%15s][%d]\n",v.c_str(),sensorTypeArray[i]);
                 }
         #endif
 }
References jsonObject_stype(), sensorTypeArray, st_soilmoisture, st_unk, and sTypeToString().
jsonObject_domoticz_modulesValue() [1/2]
void moduleManagment::jsonObject_domoticz_modulesValue (int pos, JsonObject & root)
Definition at line 237 of file adriiot_modulemanagment.h.
{
         int             id;
         mSensorType      sType;
                 moduleClassArray[pos]->id_get(id);
                 moduleClassArray[pos]->sType_get(sType);
                 moduleClassArray[pos]->json_domoticz_value(root);
 }
References moduleClass::id_get(), moduleClass::json_domoticz_value(), moduleClassArray, and moduleClass::sType_get().
Referenced by json_domoticz_modulesValue().
jsonObject_domoticz_modulesValue() [2/2]
void moduleManagment::jsonObject_domoticz_modulesValue (JsonObject & root)
Definition at line 199 of file adriiot_modulemanagment.h.
{
         int             id;
         mSensorType      sType;
         for (int i = 0; i < _pos; ++i) {
                 JsonObject object = root.createNestedObject(String(i));
                 moduleClassArray[i]->id_get(id);
                 moduleClassArray[i]->sType_get(sType);
                 moduleClassArray[i]->json_domoticz_value(object);
         }
 }
References _pos, moduleClass::id_get(), moduleClass::json_domoticz_value(), moduleClassArray, and moduleClass::sType_get().
jsonObject_mName()
void moduleManagment::jsonObject_mName (JsonObject & root)
Definition at line 306 of file adriiot_modulemanagment.h.
{
     for (int i = mn_sensor; i < mn_unk; ++i) {
         String value = "";
         mNameToString( mModuleArray[i], value);
         object[String(i)] = value;
     }
 }
References mModuleArray, mn_sensor, mn_unk, and mNameToString().
Referenced by json_mName().
jsonObject_modules()
void moduleManagment::jsonObject_modules (JsonObject & root)
Definition at line 174 of file adriiot_modulemanagment.h.
{
         for (int i = 0; i < _pos; ++i) {
                 moduleClassArray[i]->json(root);
         }
 }
References _pos, moduleClass::json(), and moduleClassArray.
Referenced by json_modules(), and json_modulesValueList().
jsonObject_modulesValue() [1/3]
void moduleManagment::jsonObject_modulesValue (int pos, JsonObject & root)
Definition at line 127 of file adriiot_modulemanagment.h.
{
         int             id;
         mSensorType      sType;
         moduleClassArray[pos]->id_get(id);
         moduleClassArray[pos]->sType_get(sType);
         moduleClassArray[pos]->json_value(root);
 }
References moduleClass::id_get(), moduleClass::json_value(), moduleClassArray, and moduleClass::sType_get().
jsonObject_modulesValue() [2/3]
void moduleManagment::jsonObject_modulesValue (JsonObject & root)
Definition at line 104 of file adriiot_modulemanagment.h.
{
         int             id;
         mSensorType      sType;
         for (int i = 0; i < _pos; ++i) {
                 moduleClassArray[i]->id_get(id);
                 moduleClassArray[i]->sType_get(sType);
                 moduleClassArray[i]->json_value(root);
         }
 }
References _pos, moduleClass::id_get(), moduleClass::json_value(), moduleClassArray, and moduleClass::sType_get().
Referenced by json_modulesValue(), and json_modulesValueList().
jsonObject_modulesValue() [3/3]
void moduleManagment::jsonObject_modulesValue (String pos, JsonObject & root)
Definition at line 150 of file adriiot_modulemanagment.h.
{
         int pos = -1;
         getByName(name, pos);
         if (pos == -1) return;
         moduleClassArray[pos]->json_value(root);
 }
References getByName(), moduleClass::json_value(), and moduleClassArray.
jsonObject_mType()
void moduleManagment::jsonObject_mType (JsonObject & root)
Definition at line 340 of file adriiot_modulemanagment.h.
{
     for (int i = mt_sensor; i < mt_unk; ++i) {
         String value = "";
         mTypeToString( mTypeArray[i], value);
         object[String(i)] = value;
     }
 }
References mt_sensor, mt_unk, mTypeArray, and mTypeToString().
Referenced by json_mType().
jsonObject_rtype()
void moduleManagment::jsonObject_rtype (JsonObject & object)
Definition at line 371 of file adriiot_modulemanagment.h.
{
     for (int i = rt_light; i < rt_unk; ++i) {
         String value = "";
         rTypeToString( rTypeArray[i], value);
         object[String(i)] = value;
     }
 }
References rt_light, rt_unk, rTypeArray, and rTypeToString().
Referenced by json_rType().
jsonObject_stype()
void moduleManagment::jsonObject_stype (JsonObject & object)
Definition at line 404 of file adriiot_modulemanagment.h.
{
     for (int i = st_soilmoisture; i < st_unk; ++i) {
         String value = "";
         sTypeToString( sensorTypeArray[i], value);
         object[String(i)] = value;
     }
 }
References sensorTypeArray, st_soilmoisture, st_unk, and sTypeToString().
Referenced by json_sType().
mNameToString()
void moduleManagment::mNameToString (mModule value, String & result)
Definition at line 265 of file adriiot_modulemanagment.h.
{
         switch (value) {
             case mn_sensor:             result = "capteur";                                     break;
             case mn_relay:                      result = "relay";                                       break;
             case mn_light:                      result = "luminaire";                           break;
             default:                            result = "";                                            break;
         }
 }
References mn_light, mn_relay, and mn_sensor.
Referenced by json_mName(), jsonObject_mName(), and moduleClass::print().
module()
moduleClass * moduleManagment::module (int pos)
Definition at line 67 of file adriiot_modulemanagment.h.
{
         return moduleClassArray[pos];
 }
References moduleClassArray.
modulesValue_check()
void moduleManagment::modulesValue_check ()
Definition at line 438 of file adriiot_modulemanagment.h.
{
         if (modulesValue_checkTimer->loop()) {
                 if (modulesValue_checkTimer->_duration_max != 1000) modulesValue_checkTimer->set_duration_max(1000);
                 const size_t serializeSize = 512 ;
                 int             id;
                 int                     nameId;
                 String          s;
                 String          n;
                 mSensorType      sType;
                 mType           moduleType;
                 int             debug = 0;
                 for (int i = 0; i < _pos; ++i) {
                         json_modulesValue(i, s, -2);
                         moduleClassArray[i]->username_get(n);
                         if ( s == "{\"mValue\":{}}" ) {
                                 #ifdef DEBUG
                                         ADRI_LOG(debug, 2, 2,"%s [next]\n",n.c_str());
                                         // fsprintf("[next]\n");
                                 #endif
                                 continue;
                         }
                         moduleClassArray[i]->mType_get(moduleType);
                         if (moduleType == mt_sensor) {
                                 moduleClassArray[i]->sType_get(sType);
                                 moduleClassArray[i]->nameId_get(nameId);
                                 moduleClassArray[i]->id_get(id);
                                 if ( modulesValue[i] == "") {
                                         ADRI_LOG(debug, -1, 0, "<<<", "");
                                         ADRI_LOG(debug, 0, 2, "%s",n.c_str());
                                         modulesValue[i] = s;
                                         #ifdef DEBUG
                                                 fsprintf("[%S] value Changed\n\t%s\n", n.c_str(), s.c_str());
                                         #endif
                                         adriiot_mainPtr->dashboard_webClient_update(i, debug);
                                         ADRI_LOG(debug, 1, 2, "","");
                                         ADRI_LOG(debug, -1, 0, ">>>", "");
                                 } else {
                                     DynamicJsonDocument object(serializeSize);
                                     deserializeJson(object, s);
                                         float v1 = object[F("mValue")][String(nameId)][F("v1")].as<float>();
                                         deserializeJson(object,  modulesValue[i]);
                                         float v2 = object[F("mValue")][String(nameId)][F("v1")].as<float>();
                                         float diff=0;
                                         if (v1>v2)      diff = v1-v2;
                                         else            diff = v2-v1;
                                         if (sType==st_soilmoisture) {
                                                 if (diff>5 ) {
                                                         ADRI_LOG(debug, -1, 0, "<<<", "");
                                                         ADRI_LOG(debug, 0, 2, "%s", n.c_str());
                                                         modulesValue[i] = s;
                                                         #ifdef DEBUG
                                                                 fsprintf("[%S] st_soilmoisture ar changed\n\t[v1: %.2f - v2: %.2f] %s\n", n.c_str() ,v1, v2, s.c_str());
                                                         #endif
                                                         adriiot_mainPtr->dashboard_webClient_update(i, debug);
                                                         ADRI_LOG(debug, 1, 2, "","");
                                                         ADRI_LOG(debug, -1, 0, ">>>", "");
                                                 }
                                         }
                                         if (sType==st_dht22) {
                                                 if (diff>=(float)0.2 ) {
                                                         ADRI_LOG(debug, -1, 0, "<<<", "");
                                                         ADRI_LOG(debug, 0, 2, "%s", n.c_str());
                                                         modulesValue[i] = s;
                                                         #ifdef DEBUG
                                                                 fsprintf("[%S] st_dht22 ar changed\n\t[v1: %.2f - v2: %.2f] %s\n", n.c_str() ,v1, v2, s.c_str());
                                                         #endif
                                                         adriiot_mainPtr->dashboard_webClient_update(i, debug);
                                                         ADRI_LOG(debug, 1, 2, "","");
                                                         ADRI_LOG(debug, -1, 0, ">>>", "");
                                                 }
                                         }
                                         if (sType==st_ds18b20) {
                                                 if (diff>=(float)0.8 ) {
                                                         ADRI_LOG(debug, -1, 0, "<<<", "");
                                                         ADRI_LOG(debug, 0, 2, "%s",n.c_str());
                                                         modulesValue[i] = s;
                                                         #ifdef DEBUG
                                                                 fsprintf("[%S] st_ds18b20 ar changed\n\t[v1: %.2f - v2: %.2f] %s\n", n.c_str() ,v1, v2, s.c_str());
                                                         #endif
                                                         adriiot_mainPtr->dashboard_webClient_update(i, debug);
                                                         ADRI_LOG(debug, 1, 2, "","");
                                                         ADRI_LOG(debug, -1, 0, ">>>", "");
                                                 }
                                         }
                                 }
                         } else {
                                 if (s != modulesValue[i]) {
                                         ADRI_LOG(debug, -1, 0, "<<<", "");
                                         ADRI_LOG(debug, 0, 2, "%s", n.c_str());
                                         modulesValue[i] = s;
                                         #ifdef DEBUG
                                                 fsprintf("[%S] value Changed\n\t%s\n", n.c_str(), s.c_str());
                                         #endif
                                         adriiot_mainPtr->dashboard_webClient_update(i, debug);
                                         ADRI_LOG(debug, 1, 2, "","");
                                         ADRI_LOG(debug, -1, 0, ">>>", "");
                                 }
                         }
                 }
         }
 }
References _pos, adriiot_mainPtr, adriiot_main::dashboard_webClient_update(), moduleClass::id_get(), json_modulesValue(), moduleClassArray, modulesValue, modulesValue_checkTimer, mt_sensor, moduleClass::mType_get(), moduleClass::nameId_get(), st_dht22, st_ds18b20, st_soilmoisture, moduleClass::sType_get(), and moduleClass::username_get().
Referenced by adriiot_main::loop().
mqqt_setidx()
void moduleManagment::mqqt_setidx (int idx)
Definition at line 17 of file adriiot_modulemanagment.h.
 {;}
mTypeToString()
void moduleManagment::mTypeToString (mType value, String & result)
Definition at line 273 of file adriiot_modulemanagment.h.
{
         switch (value) {
             case mt_sensor:                     result = "sensor";                      break;
             case mt_relay:                      result = "relay";                       break;
             case mt_lightDimmer:        result = "lightDimmer";         break;
             case mt_lightRGB:           result = "lightRGB";            break;
             case mt_lightRGBW:          result = "lightRGBW";           break;
             default:                            result = "";                            break;
         }
 }
References mt_lightDimmer, mt_lightRGB, mt_lightRGBW, mt_relay, and mt_sensor.
Referenced by json_mType(), jsonObject_mType(), and moduleClass::print().
print()
void moduleManagment::print ()
Definition at line 73 of file adriiot_modulemanagment.h.
{
         fsprintf("\n[moduleManagment::print]\n");
         for (int i = 0; i < _pos; ++i) {
                 moduleClassArray[i]->print();
         }
 }
References _pos, moduleClassArray, and moduleClass::print().
rTypeToString()
void moduleManagment::rTypeToString (mRelayType value, String & result)
Definition at line 283 of file adriiot_modulemanagment.h.
{
         switch (value) {
             case rt_light:                      result = "luminaire";                                   break;
             case rt_plug:                       result = "prise de courrant";                   break;
             default:                            result = "";                                                    break;
         }
 }
References rt_light, and rt_plug.
Referenced by json_rType(), jsonObject_rtype(), and moduleClass::print().
sTypeToString()
void moduleManagment::sTypeToString (mSensorType value, String & result)
Definition at line 290 of file adriiot_modulemanagment.h.
{
         switch (value) {
             case st_soilmoisture:       result = "soilmoisture";        break;
             case st_dht22:                      result = "dht22";               break;
             case st_ds18b20:            result = "ds18b20";             break;
             default:                            result = "";                    break;
         }
 }
References st_dht22, st_ds18b20, and st_soilmoisture.
Referenced by json_sType(), jsonObject_stype(), and moduleClass::print().
toggleRelay()
void moduleManagment::toggleRelay (unsigned long delay)
Definition at line 773 of file adriiot_modulemanagment.h.
{
         static boolean state = false;
         if (!timer_test->loop(delay)) return;
         int id = -1;
         for (int i = 0; i < _pos; ++i) {
                 moduleClassArray[i]->id_get(id);
                 if (state) {
                         adriiot_mainPtr->_relayManagment->module(id)->open();
                 } else {
                         adriiot_mainPtr->_relayManagment->module(id)->close();
                 }
         }
         state = !state;
 }
References _pos, adriiot_main::_relayManagment, adriiot_mainPtr, moduleClass::id_get(), moduleClassArray, and timer_test.
Member Data Documentation
_pos
int moduleManagment::_pos = 0
Definition at line 98 of file adriiot_main.h.
Referenced by create(), currentCnt(), getByName(), getIdByName(), json_domoticz_modulesValue(), jsonObject_domoticz_modulesValue(), jsonObject_modules(), jsonObject_modulesValue(), modulesValue_check(), print(), toggleRelay(), and adriiot_domoticz::update_module().
modulesValue
String moduleManagment::modulesValue[MAX_MODULE]
Definition at line 104 of file adriiot_main.h.
Referenced by modulesValue_check(), and adriiot_domoticz::update_module().
modulesValue_check_skip
boolean moduleManagment::modulesValue_check_skip = false
Definition at line 103 of file adriiot_main.h.
modulesValue_checkTimer
adri_timer* moduleManagment::modulesValue_checkTimer
Definition at line 106 of file adriiot_main.h.
Referenced by moduleManagment(), modulesValue_check(), and adriiot_domoticz::update_module().
The documentation for this class was generated from the following files:
adriiot_main.h
adriiot_modulemanagment.h