adri_tools_v2: moduleClass Class Reference
moduleClass Class Reference
#include <adriiot_main.h>
Public Member Functions
moduleClass (mModule mName, mType moType, mRelayType rType, mSensorType sType, int pin, int numLeds, String username)
moduleClass (mModule name, mType module_type, mRelayType relay_type, mSensorType sType, int pin, String username)
void id_get (int &ret)
void nameId_get (int &ret)
void sType_get (mSensorType &ret)
void mType_get (mType &ret)
void username_get (String &ret)
void create ()
void print ()
void json_value (JsonObject &root)
void json_domoticz_value (JsonObject &root)
void json (JsonObject &root)
Public Attributes
int _mqttidx = -1
int _numLeds = -1
Private Attributes
String _name = "myModule"
int _nameId = -1
mModule _mName = mn_unk
mType _mType = mt_unk
mRelayType _rType = rt_unk
mSensorType _sType = st_unk
int _pin = -1
int _id = -1
Detailed Description
Definition at line 52 of file adriiot_main.h.
Constructor & Destructor Documentation
moduleClass() [1/2]
moduleClass::moduleClass (mModule mName, mType moType, mRelayType rType, mSensorType sType, int pin, int numLeds, String username)
Definition at line 2 of file adriiot_moduleclass.h.
{
         _nameId         = adriiot_moduleManagemnt.currentCnt();
         _name           = username;
         _mName          = mName;
         _mType          = moType;
         _rType          = rType;
         _sType          = sType;
         _pin            = pin;
         _numLeds        = numLeds;
         create();
 }
References _mName, _mType, _name, _nameId, _numLeds, _pin, _rType, _sType, adriiot_moduleManagemnt, create(), and moduleManagment::currentCnt().
moduleClass() [2/2]
moduleClass::moduleClass (mModule name, mType module_type, mRelayType relay_type, mSensorType sType, int pin, String username)
Definition at line 14 of file adriiot_moduleclass.h.
{
         _nameId = adriiot_moduleManagemnt.currentCnt();
         _name   = username;
         _mName  = mName;
         _mType  = moType;
         _rType  = rType;
         _sType  = sType;
         _pin    = pin;
         create();
 }
References _mName, _mType, _name, _nameId, _pin, _rType, _sType, adriiot_moduleManagemnt, create(), and moduleManagment::currentCnt().
Member Function Documentation
create()
void moduleClass::create ()
Definition at line 116 of file adriiot_moduleclass.h.
{
         switch (_mType) {
             case mt_sensor:
                 switch (_sType) {
                         case st_soilmoisture:
                                         adriiot_mainPtr->_soilmoistureManagment->create(false, _pin, _id);
                         break;
                         case st_dht22:
                                         adriiot_mainPtr->_dht22Managment->create(_pin, _id);
                         break;
                         case st_ds18b20:
                                         adriiot_mainPtr->_ds18b20managment->create(_pin, _id);
                         break;
                         default:
                                 break;
                 }
             break;
             case mt_relay:
                 adriiot_mainPtr->_relayManagment->create(_pin, _id);
             break;
             case mt_lightDimmer:
                 adriiot_mainPtr->_lightDimmerManagment->create(_pin, _id);
             break;
             case mt_lightRGB:
                 adriiot_mainPtr->_RGBneoManagment->create(_id, _numLeds, _pin, 0);
             break;
             case mt_lightRGBW:
                 adriiot_mainPtr->_relayManagment->create(_pin, _id);
             break;
             default:
                 break;
         }
 }
References adriiot_main::_dht22Managment, adriiot_main::_ds18b20managment, _id, adriiot_main::_lightDimmerManagment, _mType, _numLeds, _pin, adriiot_main::_relayManagment, adriiot_main::_RGBneoManagment, adriiot_main::_soilmoistureManagment, _sType, adriiot_mainPtr, mt_lightDimmer, mt_lightRGB, mt_lightRGBW, mt_relay, mt_sensor, st_dht22, st_ds18b20, and st_soilmoisture.
Referenced by moduleClass().
id_get()
void moduleClass::id_get (int & ret)
Definition at line 153 of file adriiot_moduleclass.h.
 {ret = _id;}
References _id.
Referenced by moduleManagment::getIdByName(), moduleManagment::getIdByPos(), moduleManagment::json_domoticz_modulesValue(), moduleManagment::jsonObject_domoticz_modulesValue(), moduleManagment::jsonObject_modulesValue(), moduleManagment::modulesValue_check(), moduleManagment::toggleRelay(), and adriiot_domoticz::update_module().
json()
void moduleClass::json (JsonObject & root)
Definition at line 253 of file adriiot_moduleclass.h.
{
         JsonObject object = root.createNestedObject(String(_nameId));
         object[F("1")]  = _name;
         object[F("2")]  = _mName;
         object[F("3")]  = _mType;
         object[F("4")]  = _rType;
         object[F("5")]  = _sType;
         object[F("6")]  = _pin;
         object[F("7")]  = _id;
         object[F("8")]  = _numLeds;
 }
References _id, _mName, _mType, _name, _nameId, _numLeds, _pin, _rType, and _sType.
Referenced by moduleManagment::jsonObject_modules().
json_domoticz_value()
void moduleClass::json_domoticz_value (JsonObject & root)
Definition at line 163 of file adriiot_moduleclass.h.
{
         // JsonObject object = root.createNestedObject(String(_nameId));
         object[F("idx")] = _mqttidx;
         switch (_mType) {
             case mt_sensor:
                 switch (_sType) {
                         case st_soilmoisture:
                                 // object[F("command")] = F("udevice");
                                         adriiot_mainPtr->_soilmoistureManagment->module(_id)->domoticzJson(object);
                         break;
                         case st_dht22:
                                 // object[F("command")] = F("udevice");
                                         adriiot_mainPtr->_dht22Managment->module(_id)->domoticzJson(object);
                         break;
                         case st_ds18b20:
                                 // object[F("command")] = F("udevice");
                                         adriiot_mainPtr->_ds18b20managment->module(_id)->domoticzJson(object);
                         break;
                         default:
                                 break;
                 }
             break;
             case mt_relay:
                 switch (_rType) {
                         case rt_plug:
                                 object[F("command")] = F("switchlight");
                                         adriiot_mainPtr->_relayManagment->module(_id)->domoticzJson(object);
                         break;
                         case rt_light:
                                 object[F("command")] = F("switchlight");
                                         adriiot_mainPtr->_relayManagment->module(_id)->domoticzJson(object);
                         break;
                         default:
                                 break;
                 }
             break;
             case mt_lightDimmer:
                         adriiot_mainPtr->_lightDimmerManagment->module(_id)->domoticzJson(object);
             break;
             case mt_lightRGB:
                         adriiot_mainPtr->_RGBneoManagment->module(_id)->domoticzJson(object);
             break;
             case mt_lightRGBW:
                         adriiot_mainPtr->_relayManagment->module(_id)->domoticzJson(object);
             break;
             default:
                 break;
         }
 }
References adriiot_main::_dht22Managment, adriiot_main::_ds18b20managment, _id, adriiot_main::_lightDimmerManagment, _mqttidx, _mType, adriiot_main::_relayManagment, adriiot_main::_RGBneoManagment, _rType, adriiot_main::_soilmoistureManagment, _sType, adriiot_mainPtr, mt_lightDimmer, mt_lightRGB, mt_lightRGBW, mt_relay, mt_sensor, rt_light, rt_plug, st_dht22, st_ds18b20, and st_soilmoisture.
Referenced by moduleManagment::json_domoticz_modulesValue(), and moduleManagment::jsonObject_domoticz_modulesValue().
json_value()
void moduleClass::json_value (JsonObject & root)
Definition at line 215 of file adriiot_moduleclass.h.
{
         JsonObject object = root.createNestedObject(String(_nameId));
         switch (_mType) {
             case mt_sensor:
                 switch (_sType) {
                         case st_soilmoisture:
                                         adriiot_mainPtr->_soilmoistureManagment->module(_id)->json(object);
                         break;
                         case st_dht22:
                                          adriiot_mainPtr->_dht22Managment->module(_id)->json(object);
                         break;
                         case st_ds18b20:
                                          adriiot_mainPtr->_ds18b20managment->module(_id)->json(object);
                         break;
                         default:
                                 break;
                 }
             break;
             case mt_relay:
                 adriiot_mainPtr->_relayManagment->module(_id)->json(object);
             break;
             case mt_lightDimmer:
                 adriiot_mainPtr->_lightDimmerManagment->module(_id)->json(object);
             break;
             case mt_lightRGB:
                 adriiot_mainPtr->_RGBneoManagment->module(_id)->json(object);
             break;
             case mt_lightRGBW:
                 adriiot_mainPtr->_relayManagment->module(_id)->json(object);
             break;
             default:
                 break;
         }
 }
References adriiot_main::_dht22Managment, adriiot_main::_ds18b20managment, _id, adriiot_main::_lightDimmerManagment, _mType, _nameId, adriiot_main::_relayManagment, adriiot_main::_RGBneoManagment, adriiot_main::_soilmoistureManagment, _sType, adriiot_mainPtr, mt_lightDimmer, mt_lightRGB, mt_lightRGBW, mt_relay, mt_sensor, st_dht22, st_ds18b20, and st_soilmoisture.
Referenced by moduleManagment::jsonObject_modulesValue().
mType_get()
void moduleClass::mType_get (mType & ret)
Definition at line 159 of file adriiot_moduleclass.h.
 {ret = _mType;}
References _mType.
Referenced by moduleManagment::modulesValue_check(), and adriiot_domoticz::update_module().
nameId_get()
void moduleClass::nameId_get (int & ret)
Definition at line 154 of file adriiot_moduleclass.h.
 {ret = _nameId;}
References _nameId.
Referenced by moduleManagment::modulesValue_check().
print()
void moduleClass::print ()
Definition at line 28 of file adriiot_moduleclass.h.
{
         float           temperature;
         float           temperatureIndice;
         int             value;
         boolean         state;
         String          sName;
         String          sType;
         String          seType;
         String          mRelayType;
         adriiot_moduleManagemnt.mNameToString(_mName, sName);
         adriiot_moduleManagemnt.mTypeToString(_mType, sType);
         adriiot_moduleManagemnt.sTypeToString(_sType, seType);
         adriiot_moduleManagemnt.rTypeToString(_rType, mRelayType);
         fsprintf("[id: %4d][pin: %4d][name: %-15s][module: %15s][type: %15s]",
                 _id,
                 _pin,
                 _name.c_str(),
                 sName.c_str(),
                 sType.c_str()
         );
         int valueMod = 0;
         switch (_mType) {
             case mt_sensor:
                 switch (_sType) {
                         case st_soilmoisture:
                                 adriiot_mainPtr->_soilmoistureManagment->module(_id)->read(value);
                                 valueMod = 1;
                         break;
                         case st_dht22:
                                 adriiot_mainPtr->_dht22Managment->module(_id)->read_temperature(temperature, state);
                                 adriiot_mainPtr->_dht22Managment->module(_id)->read_temperatureIndice(temperatureIndice, state);
                                 valueMod = 2;
                         break;
                         case st_ds18b20:
                                 adriiot_mainPtr->_ds18b20managment->module(_id)->read_temperature(temperature, state);
                                 valueMod = 2;
                         break;
                         default:
                                 break;
                 }
             break;
             case mt_relay:
                 switch (_rType) {
                         case rt_light:
                                         adriiot_mainPtr->_relayManagment->module(_id)->getStatus(state);
                         break;
                         case rt_plug:
                                         adriiot_mainPtr->_relayManagment->module(_id)->getStatus(state);
                         break;
                         default:
                                 break;
                 }
             break;
             case mt_lightDimmer:
                         adriiot_mainPtr->_lightDimmerManagment->module(_id)->getStatus(state);
             break;
             case mt_lightRGB:
                         adriiot_mainPtr->_RGBneoManagment->module(_id)->getStatus(state);
             break;
             case mt_lightRGBW:
                         adriiot_mainPtr->_relayManagment->module(_id)->getStatus(state);
             break;
             default:
                 break;
         }
         switch (valueMod) {
             case 0:
                 fsprintf("[mRelayType: %18s][seType: %15s][statu: %10d]\n", mRelayType.c_str(), seType.c_str(), state);
             break;
             case 1:
                 fsprintf("[mRelayType: %18s][seType: %15s][statu: %10d]\n", mRelayType.c_str(), seType.c_str(), value);
             break;
             case 2:
                 fsprintf("[mRelayType: %18s][seType: %15s][statu: %10.2f]\n", mRelayType.c_str(), seType.c_str(), temperature);
             break;
             default:
                 break;
         }
 }
References adriiot_main::_dht22Managment, adriiot_main::_ds18b20managment, _id, adriiot_main::_lightDimmerManagment, _mName, _mType, _name, _pin, adriiot_main::_relayManagment, adriiot_main::_RGBneoManagment, _rType, adriiot_main::_soilmoistureManagment, _sType, adriiot_mainPtr, adriiot_moduleManagemnt, moduleManagment::mNameToString(), mt_lightDimmer, mt_lightRGB, mt_lightRGBW, mt_relay, mt_sensor, moduleManagment::mTypeToString(), rt_light, rt_plug, moduleManagment::rTypeToString(), st_dht22, st_ds18b20, st_soilmoisture, and moduleManagment::sTypeToString().
Referenced by moduleManagment::print().
sType_get()
void moduleClass::sType_get (mSensorType & ret)
Definition at line 158 of file adriiot_moduleclass.h.
 {ret = _sType;}
References _sType.
Referenced by moduleManagment::json_domoticz_modulesValue(), moduleManagment::jsonObject_domoticz_modulesValue(), moduleManagment::jsonObject_modulesValue(), moduleManagment::modulesValue_check(), and adriiot_domoticz::update_module().
username_get()
void moduleClass::username_get (String & ret)
Definition at line 152 of file adriiot_moduleclass.h.
 {ret = _name;}
References _name.
Referenced by moduleManagment::getByName(), moduleManagment::getIdByName(), moduleManagment::json_domoticz_modulesValue(), moduleManagment::modulesValue_check(), and adriiot_domoticz::update_module().
Member Data Documentation
_id
int moduleClass::_id = -1 private
Definition at line 62 of file adriiot_main.h.
Referenced by create(), id_get(), json(), json_domoticz_value(), json_value(), and print().
_mName
mModule moduleClass::_mName = mn_unk private
Definition at line 57 of file adriiot_main.h.
Referenced by json(), moduleClass(), and print().
_mqttidx
int moduleClass::_mqttidx = -1
Definition at line 64 of file adriiot_main.h.
Referenced by moduleManagment::create(), and json_domoticz_value().
_mType
mType moduleClass::_mType = mt_unk private
Definition at line 58 of file adriiot_main.h.
Referenced by create(), json(), json_domoticz_value(), json_value(), moduleClass(), mType_get(), and print().
_name
String moduleClass::_name = "myModule" private
Definition at line 55 of file adriiot_main.h.
Referenced by json(), moduleClass(), print(), and username_get().
_nameId
int moduleClass::_nameId = -1 private
Definition at line 56 of file adriiot_main.h.
Referenced by json(), json_value(), moduleClass(), and nameId_get().
_numLeds
int moduleClass::_numLeds = -1
Definition at line 65 of file adriiot_main.h.
Referenced by create(), json(), and moduleClass().
_pin
int moduleClass::_pin = -1 private
Definition at line 61 of file adriiot_main.h.
Referenced by create(), json(), moduleClass(), and print().
_rType
mRelayType moduleClass::_rType = rt_unk private
Definition at line 59 of file adriiot_main.h.
Referenced by json(), json_domoticz_value(), moduleClass(), and print().
_sType
mSensorType moduleClass::_sType = st_unk private
Definition at line 60 of file adriiot_main.h.
Referenced by create(), json(), json_domoticz_value(), json_value(), moduleClass(), print(), and sType_get().
The documentation for this class was generated from the following files:
adriiot_main.h
adriiot_moduleclass.h